# Generated by Django 4.2.3 on 2023-07-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'login'},
        ),
    ]
