# Generated by Django 4.2.3 on 2023-07-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_signup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
    ]
